return {
  "SmiteshP/nvim-navic",
  dependencies = { "neovim/nvim-lspconfig" },
  opts = {
    highlight = true,
    separator = " > ",
    depth_limit = 5,
    depth_limit_indicator = "..",
    safe_output = true,
    click = true,
    lsp = {
      auto_attach = false, -- we attach manually in LspAttach for control
    },
    icons = {
      File = "󰈙 ",
      Module = " ",
      Namespace = "󰌗 ",
      Package = " ",
      Class = "󰠱 ",
      Method = "󰆧 ",
      Property = "󰜢 ",
      Field = "󰜢 ",
      Constructor = " ",
      Enum = " ",
      Interface = " ",
      Function = "󰊕 ",
      Variable = "󰀫 ",
      Constant = "󰏿 ",
      String = " ",
      Number = "󰎠 ",
      Boolean = " ",
      Array = "󰅪 ",
      Object = "󰅩 ",
      Key = "󰌋 ",
      Null = "󰟢 ",
      EnumMember = " ",
      Struct = "󰙅 ",
      Event = " ",
      Operator = "󰆕 ",
      TypeParameter = "󰊄 ",
    },
  },
}
