-- Theme colours.
--
-- `colors.lua` is regenerated by scripts/theme_apply.sh and is gitignored.
-- It is loaded defensively: a missing or broken colors.lua falls back to the
-- palette below instead of taking the whole config down with it (which is what
-- used to happen under the old hyprlang config when the generated colours
-- went missing and $theme_border was left unset).

local fallback = {
    bg              = "rgb(282828)",
    mantle          = "rgb(1d2021)",
    crust           = "rgb(161616)",
    surface0        = "rgb(3c3836)",
    surface1        = "rgb(504945)",
    text            = "rgb(ebdbb2)",
    accent          = "rgb(fabd2f)",
    border          = "rgba(665c54aa)",
    border_inactive = "rgba(16161666)",
    red             = "rgb(fb4934)",
    green           = "rgb(b8bb26)",
    yellow          = "rgb(fabd2f)",
    blue            = "rgb(83a598)",
    mauve           = "rgb(d3869b)",
    rounding        = 16,
}

local ok, generated = pcall(require, "colors")

local theme = {}
for k, v in pairs(fallback) do
    theme[k] = v
end

if ok and type(generated) == "table" then
    for k, v in pairs(generated) do
        theme[k] = v
    end
end

-- Exposed as a global so every required file can reach it without each one
-- re-running the pcall. (require() is scoped per-file by Hyprland.)
Theme = theme

return theme
